### ISSUE TITLE
atd_ranking을 main으로 변경

### ISSUE THREAD

**Issue by Keunmo** [Keunmo/jaram-attendance#27]
atd_ranking.html이나 views에 있는 atd_ranking을 전부 main이라는 이름으로 바꾸고 
1등부터 3등까지만 표가 아닌 순위 아이콘으로 표시하고 '웹실에 오셔서 자신의 출석 순위를 높이세요' 와 같은 문구도 넣고 정말 뭔가 메인화면스럽게 바꾸는거 어떨까?

**Comment by Taewan-P** [comment]
구체적인 설명이 필요하다...메인화면 스럽게라고 하면 모름
